-- Schema des Moduls `ext_stammdaten`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS ext_stammdaten;

-- =============================================================================================
-- ext_stammdaten: mock of the external person register
-- =============================================================================================

CREATE TABLE ext_stammdaten.person (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kvnr         VARCHAR(20)  NOT NULL,
    name         VARCHAR(255),
    vorname      VARCHAR(255),
    geburtsdatum DATE,
    strasse      VARCHAR(255),
    hausnummer   VARCHAR(20),
    plz          VARCHAR(10),
    ort          VARCHAR(255),
    CONSTRAINT ux_person_kvnr UNIQUE (kvnr)
);

-- A Freischaltcode belongs to the register, not to the ident tool that checks it (ADR-31): the
-- register issues it, the ident tool only asks whether a given one is valid. Only the digest lives
-- here - what id_fsc compares against.
CREATE TABLE ext_stammdaten.freischaltcode (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id  BIGINT      NOT NULL,
    code_hash  VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_freischaltcode_person FOREIGN KEY (person_id) REFERENCES ext_stammdaten.person (id) ON DELETE CASCADE
);
CREATE INDEX ix_freischaltcode_person_id_code_hash ON ext_stammdaten.freischaltcode (person_id, code_hash);

-- The simulated letter that carries a Freischaltcode to the person. The plaintext exists only here,
-- as it does in the real world on paper (demo frame, like ADR-22) - the demo reads it back from the
-- "mailbox" instead of keeping a second hard-coded list of codes.
CREATE TABLE ext_stammdaten.brief (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id          BIGINT      NOT NULL,
    freischaltcode_id  BIGINT      NOT NULL,
    code               VARCHAR(64) NOT NULL,
    versandt_am        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_brief_person FOREIGN KEY (person_id) REFERENCES ext_stammdaten.person (id) ON DELETE CASCADE,
    CONSTRAINT fk_brief_freischaltcode FOREIGN KEY (freischaltcode_id) REFERENCES ext_stammdaten.freischaltcode (id) ON DELETE CASCADE
);
CREATE INDEX ix_brief_person_id ON ext_stammdaten.brief (person_id);
