-- Schema des Moduls `ext_stammdaten`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS ext_stammdaten;

-- =============================================================================================
-- ext_stammdaten: mock of the external person register
-- =============================================================================================

CREATE TABLE ext_stammdaten.person (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kvnr         VARCHAR(20)  NOT NULL,
    name         VARCHAR(255),
    vorname      VARCHAR(255),
    geburtsdatum DATE,
    strasse      VARCHAR(255),
    hausnummer   VARCHAR(20),
    plz          VARCHAR(10),
    ort          VARCHAR(255),
    CONSTRAINT ux_person_kvnr UNIQUE (kvnr)
);
