-- Was eine Kontoloeschung ueberlebt (ADR-39, Review 2026-09 Schritt 29): ein append-only Protokoll
-- DASS und WIE etwas geschah - nie WAS. Keine Attributwerte, keine Stammdaten, keine
-- Dokumentnummer (§ 20 PAuswG).
--
-- Feste Spalten fuer das, was jedes Ereignis hat; details (JSON) fuer das, was nur einzelne
-- Ereignisse tragen: Rolle und Referenz beim Anbieter einer Identifizierung, Nachweise und Kanal
-- einer neuen Methode, Grund einer Deaktivierung, Vertrauensanker eines Widerrufs, das andere
-- Konto einer Uebernahme. Welche Schluessel es gibt, legt ChangeLog fest - eine Methode je Ereignis.
--
-- Bewusst OHNE Fremdschluessel auf account.account: die Zeilen sollen die Loeschung ueberleben. Die
-- Wertetabellen (claim, retraction, auth_method.details, anchor) verschwinden dagegen weiter mit dem
-- Konto - das ist Datenminimierung, nicht Luecke. Nach Ablauf der Frist seit der Loeschung raeumt
-- ChangeLogRetention ab (account.change-log.retention-years).
CREATE TABLE account.change_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT       NOT NULL,
    change_type  VARCHAR(32)  NOT NULL,
    subject     VARCHAR(50),
    acr         VARCHAR(16),
    details     JSON,
    -- Suchschluessel: danach wird eine Person Jahre spaeter gefunden, unter Millionen Zeilen - je eine
    -- indizierte Spalte statt einer Suche im JSON. Nur bei IDENTIFIED gesetzt.
    lookup_key  VARCHAR(64),
    person_id   VARCHAR(64),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_change_log_type CHECK (change_type IN (
        'IDENTIFIED', 'ATTRIBUTE_RETRACTED', 'METHOD_ADDED', 'METHOD_DEACTIVATED', 'ACCOUNT_DELETED', 'ACCOUNT_ABSORBED'))
);
CREATE INDEX ix_change_log_account ON account.change_log (account_id, occurred_at);
-- Die Frage der Aufbewahrung: welche Konten sind seit wann geloescht?
CREATE INDEX ix_change_log_type_time ON account.change_log (change_type, occurred_at);
-- Die Suche nach einer Person (PersonLookupKey bzw. Registernummer), auch nach der Loeschung.
CREATE INDEX ix_change_log_lookup_key ON account.change_log (lookup_key);
CREATE INDEX ix_change_log_person_id ON account.change_log (person_id);
