-- Was eine Kontoloeschung ueberlebt (ADR-39, Review 2026-09 Schritt 29): ein append-only Protokoll
-- DASS und WIE etwas geschah - nie WAS. Keine Attributwerte, keine Stammdaten, keine Details; nur
-- Konto-Id, Ereignis, Verfahren bzw. Attributtyp, Niveau, Quelle und Zeitpunkt.
--
-- Bewusst OHNE Fremdschluessel auf account.account: die Zeilen sollen die Loeschung ueberleben. Die
-- Wertetabellen (claim, identification.details, auth_method.details, anchor) verschwinden dagegen
-- weiter mit dem Konto - das ist Datenminimierung, nicht Luecke. Nach Ablauf der Frist seit der
-- Loeschung raeumt AuditRetention ab (account.audit.retention-years).
CREATE TABLE account.audit_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT       NOT NULL,
    event_type  VARCHAR(32)  NOT NULL,
    subject     VARCHAR(50),
    acr         VARCHAR(16),
    source      VARCHAR(64),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_audit_event_type CHECK (event_type IN (
        'IDENTIFIED', 'ATTRIBUTE_RETRACTED', 'METHOD_ADDED', 'METHOD_DEACTIVATED', 'ACCOUNT_DELETED', 'ACCOUNT_ABSORBED'))
);
CREATE INDEX ix_audit_event_account ON account.audit_event (account_id, occurred_at);
-- Die Frage der Aufbewahrung: welche Konten sind seit wann geloescht?
CREATE INDEX ix_audit_event_type_time ON account.audit_event (event_type, occurred_at);
