-- Das Anmeldeprotokoll (ADR-39, Nachtrag): wer sich wann, womit und auf welchem Niveau angemeldet
-- hat, wo es fehlschlug, wann ein Konto gesperrt wurde und wann eine Sitzung endete. Anders als
-- account.change_log kein Nachweis ueber die Loeschung hinaus: es gehoert dem Konto und geht mit
-- ihm (ON DELETE CASCADE), und es lebt nur account.sign-in-log.retention-months (6 Monate).
--
-- Gleiche Form wie change_log: feste Spalten fuer das, was jedes Ereignis hat; details (JSON) mit
-- type und version fuer das Uebrige. Welche Schluessel es gibt, legt SignInLog fest.
CREATE TABLE account.sign_in_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL,
    sign_in_type VARCHAR(32) NOT NULL,
    channel      VARCHAR(16),
    acr          VARCHAR(16),
    details      JSON,
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sign_in_log_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE,
    CONSTRAINT ck_sign_in_log_type CHECK (sign_in_type IN (
        'SIGNED_IN', 'STEPPED_UP', 'SIGN_IN_FAILED', 'LOCKED_OUT', 'SIGNED_OUT'))
);
CREATE INDEX ix_sign_in_log_account ON account.sign_in_log (account_id, occurred_at);
-- Die Frage der Aufbewahrung: was ist aelter als die Frist?
CREATE INDEX ix_sign_in_log_time ON account.sign_in_log (occurred_at);
