/**
 * The client's view of the API. Everything that travels on the wire comes from
 * `./generated/models` - generated by the OpenAPI Generator from `api/openapi.yaml`, which
 * `OpenApiSnapshotTest` keeps in step with the running backend. Field names, value types and
 * which fields are optional therefore cannot drift from the Kotlin DTOs any more: a removed,
 * renamed or newly-nullable field becomes a TypeScript error rather than an `undefined` at render
 * time.
 *
 * Requiredness is carried too, not asserted here: `KotlinRequiredModelConverter` marks a property
 * required in the schema exactly when the Kotlin property is non-nullable, so the generated type
 * says `channel: ChannelBlock`, not `channel?: ChannelBlock`. Nothing in this file restates what
 * the backend already declares.
 *
 * What stays hand-written is only what the backend genuinely serves as an open map - `stepData`
 * and its `prompt`, the demo bag's named extras, the token/ID-token shapes. Their contents are
 * documented per step in docs/05-api.md, not in the schema, so there is nothing to generate from.
 */
import type * as Wire from './generated/models'

export type {
  ActiveMethodView,
  AmrEntry,
  AuthData,
  BoundCredentialView,
  ChannelBlock,
  DeviceLinkResponse,
  JourneyDebugStep,
  Next,
} from './generated/models'

/** Whatever the current step needs to render: missing fields, selection options, or a retry reason. */
export interface StepData {
  missingFields?: string[]
  options?: string[]
  title?: string
  description?: string
  error?: string
  prompt?: Prompt
  [key: string]: unknown
}

/**
 * What an AnswerableState shows while it waits for `POST .../answer` - authored entirely by the
 * backend (orchestrator/journey/state/Prompt.kt): the app channel is a mobile app with week-long
 * release cycles, so screen text must be able to change without an app release. `@t` is the
 * Jackson polymorphism discriminator; `Confirm` is the only variant today.
 *
 * Hand-written rather than generated: it only ever travels inside `stepData`, which the backend
 * serves as an open map, so it has no schema of its own to generate from.
 */
export interface Prompt {
  '@t': 'Confirm'
  title: string
  description?: string
  confirmLabel: string
  cancelLabel: string
  destructive?: boolean
}

/** One seeded demo persona - travels inside the demo bag, so it has no schema of its own. */
export interface DemoPerson {
  kvnr: string
  name: string
  vorname: string
  email: string
  strasse: string
  hausnummer: string
  plz: string
  ort: string
  geburtsdatum: string
  fscCode: string
  /** The eID card's fixed restricted identifier - person-unique, changes only with a new card. */
  restrictedId: string
}

/**
 * Demo-only values, never part of the production contract (docs/05-api.md #2). The generated type
 * carries `accountId`/`personId`/`journeys` plus an open index signature: the backend flattens
 * whatever the tool that just ran attached (@JsonAnyGetter) onto this same object. The named
 * extras below are the ones the UI actually reads, typed so a rename is noticed.
 */
export type DemoInfo = Wire.DemoInfo & {
  /** The just-issued TAN, shown so testers don't need server-log access. */
  tan?: string
  /** Fixed demo password (same value for enroll/login/lookup), prefilled so testers never have to remember one. */
  password?: string
  /** Fixed demo email (same value for enroll-email and both lookup-based logins), prefilled so testers never have to remember one. */
  email?: string
  /** All seeded demo personas, attached centrally by the orchestrator (not per tool) - offered as a picker wherever a demo value is prefilled. */
  persons?: DemoPerson[]
}

/**
 * The one response envelope for every endpoint, channel- and tool-level alike (docs/05-api.md #2).
 * Only `stepData` and `demo` are re-typed - both are open maps on the wire, and the two types
 * above are the client's own reading of them.
 */
export type ChannelResponse = Omit<Wire.ChannelResponse, 'stepData' | 'demo'> & {
  stepData?: StepData
  demo?: DemoInfo
}

/**
 * One row of the rich, per-step journey trace (GET /journey-log) - distinct from the backend's
 * minimized orchestrator.session_event audit trail. Demo/debug only: shows everything the backend
 * could determine about a journey's path, grouped client-side by channelSessionId/journeyId.
 */
export type JourneyLogEntryView = Omit<Wire.JourneyLogEntryView, 'detail'> & {
  detail: Record<string, unknown>
}

export type JourneyLogResponse = { entries: JourneyLogEntryView[] }

/**
 * App-Kanal AccessToken (docs/05-api.md #2) - je nach Backend-Profil entweder ein spec-shaped
 * unsecured JWT (alg=none, Default-Profil) oder ein echtes, von Keycloak signiertes Token
 * (keycloak-Profil); beide werden hier nur zum Anzeigen geparst, nie verifiziert. refreshToken is
 * deliberately NOT part of this shape - it is a credential and never leaves the backend, only its
 * expiry does.
 */
export type { TokenResponse } from './generated/models'

/** Fachliche ID-Token-Claims - a resource separate from the AccessToken's own claims. */
export interface IdTokenClaims {
  sub?: string
  acr?: string
  amr?: string[]
  auth_time?: number
  accountId?: number
  personId?: number
  /** "Vorname Name" of the person behind this account (PersonDirectory.displayName) - who is logged in. */
  name?: string
  email?: string
  email_verified?: boolean
  [key: string]: unknown
}
