/**
 * The client's view of the API. Everything that travels on the wire comes from
 * `./generated/models` - generated by the OpenAPI Generator from `api/openapi.yaml`, which
 * `OpenApiSnapshotTest` keeps in step with the running backend. Field names, value types and
 * which fields are optional therefore cannot drift from the Kotlin DTOs any more: a removed,
 * renamed or newly-nullable field becomes a TypeScript error rather than an `undefined` at render
 * time.
 *
 * Requiredness is carried too, not asserted here: `KotlinRequiredModelConverter` marks a property
 * required in the schema exactly when the Kotlin property is non-nullable, so the generated type
 * says `channel: ChannelBlock`, not `channel?: ChannelBlock`. Nothing in this file restates what
 * the backend already declares.
 *
 * `stepData` is generated too, as a union discriminated by `kind`. The one thing added here is the
 * way out for a shape this build does not know yet - see [StepData].
 *
 * What stays hand-written is only what the backend genuinely serves as an open map - the demo
 * bag's named extras and the token/ID-token shapes.
 */
import type * as Wire from './generated/models'

export type {
  ActiveMethodView,
  AmrEntry,
  AuthData,
  BoundCredentialView,
  ChannelBlock,
  DeviceLinkResponse,
  JourneyDebugStep,
  Next,
} from './generated/models'

/** Every step shape this build knows, generated from the contract. */
export type KnownStepData = Wire.StepData
export type StepKind = KnownStepData['kind']

/**
 * A shape this build does not know yet. The step flow is decided by the backend and may grow
 * without a frontend release - a newer backend can send a `kind` this union has never heard of,
 * and nothing may break on it. Deliberately no index signature: reading a field from an unknown
 * shape is exactly the guess the typed union is there to stop.
 */
export interface UnknownStepData {
  kind: string
}

export type StepData = KnownStepData | UnknownStepData

/**
 * The step data if it has the given shape, otherwise undefined. The one way to read `stepData`:
 * a plain `stepData.kind === 'x'` does not narrow, because [UnknownStepData] matches any string.
 */
export function stepDataOf<K extends StepKind>(
  stepData: StepData | undefined,
  kind: K,
): Extract<KnownStepData, { kind: K }> | undefined {
  return stepData?.kind === kind ? (stepData as Extract<KnownStepData, { kind: K }>) : undefined
}

/** What an AnswerableState shows while it waits - authored by the backend, see PromptView. */
export type Prompt = Wire.Prompt
export type ConfirmPrompt = Wire.Confirm

/**
 * The prompt as a yes/no confirmation, or undefined for a kind this build does not know - the
 * same rule as [UnknownStepData]: an unknown shape is not rendered, it is not guessed at.
 */
export function confirmPromptOf(prompt: Prompt | undefined): ConfirmPrompt | undefined {
  return prompt?.kind === 'Confirm' ? (prompt as ConfirmPrompt) : undefined
}

/** One seeded demo persona - travels inside the demo bag, so it has no schema of its own. */
export interface DemoPerson {
  kvnr: string
  name: string
  vorname: string
  email: string
  strasse: string
  hausnummer: string
  plz: string
  ort: string
  geburtsdatum: string
  fscCode: string
  /** The eID card's fixed restricted identifier - person-unique, changes only with a new card. */
  restrictedId: string
}

/**
 * Demo-only values, never part of the production contract (docs/05-api.md #2). The generated type
 * carries `accountId`/`personId`/`journeys` plus an open index signature: the backend flattens
 * whatever the tool that just ran attached (@JsonAnyGetter) onto this same object. The named
 * extras below are the ones the UI actually reads, typed so a rename is noticed.
 */
export type DemoInfo = Wire.DemoInfo & {
  /** The just-issued TAN, shown so testers don't need server-log access. */
  tan?: string
  /** Fixed demo password (same value for enroll/login/lookup), prefilled so testers never have to remember one. */
  password?: string
  /** Fixed demo email (same value for enroll-email and both lookup-based logins), prefilled so testers never have to remember one. */
  email?: string
  /** All seeded demo personas, attached centrally by the orchestrator (not per tool) - offered as a picker wherever a demo value is prefilled. */
  persons?: DemoPerson[]
}

/**
 * The one response envelope for every endpoint, channel- and tool-level alike (docs/05-api.md #2).
 * Only `stepData` and `demo` are re-typed: `stepData` widened by [UnknownStepData], `demo` by
 * the named extras above.
 */
export type ChannelResponse = Omit<Wire.ChannelResponse, 'stepData' | 'demo'> & {
  stepData?: StepData
  demo?: DemoInfo
}

/**
 * One row of the rich, per-step journey trace (GET /journey-log) - distinct from the backend's
 * minimized orchestrator.session_event audit trail. Demo/debug only: shows everything the backend
 * could determine about a journey's path, grouped client-side by channelSessionId/journeyId.
 */
export type JourneyLogEntryView = Omit<Wire.JourneyLogEntryView, 'detail'> & {
  detail: Record<string, unknown>
}

export type JourneyLogResponse = { entries: JourneyLogEntryView[] }

/**
 * App-Kanal AccessToken (docs/05-api.md #2) - je nach Backend-Profil entweder ein spec-shaped
 * unsecured JWT (alg=none, Default-Profil) oder ein echtes, von Keycloak signiertes Token
 * (keycloak-Profil); beide werden hier nur zum Anzeigen geparst, nie verifiziert. refreshToken is
 * deliberately NOT part of this shape - it is a credential and never leaves the backend, only its
 * expiry does.
 */
export type { TokenResponse } from './generated/models'

/** Fachliche ID-Token-Claims - a resource separate from the AccessToken's own claims. */
export interface IdTokenClaims {
  sub?: string
  acr?: string
  amr?: string[]
  auth_time?: number
  accountId?: number
  personId?: number
  /** "Vorname Name" of the person behind this account (PersonDirectory.displayName) - who is logged in. */
  name?: string
  email?: string
  email_verified?: boolean
  [key: string]: unknown
}
