-- Schema des Moduls `id_fsc`.
-- Die modulweiten Regeln (Schemabesitz, Typen, Namen) stehen in db/migration/KONVENTIONEN.md.

CREATE SCHEMA IF NOT EXISTS id_fsc;

-- =============================================================================================
-- id_fsc
-- =============================================================================================

-- A Freischaltcode stays reusable until it expires; guessing is bounded by the PERSON throttle.
CREATE TABLE id_fsc.code (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id  BIGINT      NOT NULL,
    code_hash  VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_code_person_id ON id_fsc.code (person_id, code_hash);

CREATE TABLE id_fsc.ident_tool_session (
    tool_session_id UUID PRIMARY KEY,
    kvnr            VARCHAR(20),
    person_id       BIGINT,
    name            VARCHAR(255),
    vorname         VARCHAR(255),
    fsc_hash        VARCHAR(64),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_ident_tool_session_created_at ON id_fsc.ident_tool_session (created_at);
