CREATE TABLE auth_sms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(25) NOT NULL,
    tan VARCHAR(10) NOT NULL,
    validated BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE account ADD COLUMN authentication_methods JSON DEFAULT '[]' NOT NULL;
