-- auth_device module ------------------------------------------------------

-- Long-lived, account-bound device credential: the public half of a
-- non-extractable device key pair, verified via a self-signed device-proof
-- JWT (DeviceProofValidator) rather than a server-issued secret.
CREATE TABLE device_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kty VARCHAR(10) NOT NULL,
    crv VARCHAR(10) NOT NULL,
    x VARCHAR(255) NOT NULL,
    y VARCHAR(255) NOT NULL,
    thumbprint VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped enrollment data (invariant marker: start() ran before patch()).
CREATE TABLE enroll_device_tool_data (
    tool_session_id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped auth data (resolved enrollment reference).
CREATE TABLE auth_device_tool_data (
    tool_session_id UUID PRIMARY KEY,
    enrollment_ref_type VARCHAR(50),
    enrollment_ref_id VARCHAR(50),
    created_at TIMESTAMP NOT NULL
);
