-- account module -----------------------------------------------------------
-- Log of every identity attribute ever claimed for an account, each with its own trust anchor
-- (docs/ideen/claims-modell-und-vertrauensanker.md). account.person_id remains the actively
-- consolidated projection - nothing reads this table yet, only AccountService writes to it.

CREATE TABLE account_attribute (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES account(id),
    attribute_type VARCHAR(50) NOT NULL,
    attribute_value VARCHAR(255) NOT NULL,
    trust_anchor VARCHAR(50) NOT NULL,
    established_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_account_attribute_account_id ON account_attribute(account_id);

-- Was only an application invariant (findOrCreateAccount: find before create) - the log's
-- consolidation step is the natural place to also make it a real DB guarantee.
ALTER TABLE account ADD CONSTRAINT uq_account_person_id UNIQUE (person_id);
