-- Baseline schema for the target model described in docs/02-domaenenmodell.md,
-- docs/03-tool-architektur.md and docs/06-ablaeufe.md. Replaces the incremental
-- V1-V16 history of the earlier Attempt-based model (see docs/11-umsetzungsplan.md).

-- ext_stammdaten module -----------------------------------------------------

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kvnr VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255),
    vorname VARCHAR(255),
    strasse VARCHAR(255),
    hausnummer VARCHAR(20),
    plz VARCHAR(10),
    ort VARCHAR(255)
);

-- id_fsc module ---------------------------------------------------------

CREATE TABLE fsc_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_fsc_code_person_id ON fsc_code(person_id);

CREATE TABLE id_fsc_tool_data (
    tool_session_id UUID PRIMARY KEY,
    kvnr VARCHAR(20),
    -- resolved by the orchestrator via ext_stammdaten and handed in, so id_fsc never
    -- depends on the ext_stammdaten module directly (docs/08-projektrahmen.md #3: leaf
    -- modules stay decoupled from each other).
    person_id BIGINT,
    name VARCHAR(255),
    vorname VARCHAR(255),
    fsc VARCHAR(50),
    created_at TIMESTAMP NOT NULL
);

-- auth_sms module ---------------------------------------------------------

-- Long-lived, confirmed SMS enrollment. Exists only after a successful TAN
-- check; no "validated" flag needed by definition (docs/06-ablaeufe.md #1).
CREATE TABLE auth_sms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(25) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped enrollment data (unconfirmed phone number + hashed TAN).
CREATE TABLE enroll_sms_tool_data (
    tool_session_id UUID PRIMARY KEY,
    phone_number VARCHAR(25),
    issued_tan_hash VARCHAR(255),
    tan_expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped auth data (resolved enrollment reference + hashed TAN).
CREATE TABLE auth_sms_use_tool_data (
    tool_session_id UUID PRIMARY KEY,
    enrollment_ref_type VARCHAR(50),
    enrollment_ref_id VARCHAR(50),
    issued_tan_hash VARCHAR(255),
    tan_expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

-- account module ---------------------------------------------------------

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    identifications JSON NOT NULL DEFAULT '[]',
    authentication_methods JSON NOT NULL DEFAULT '[]'
);
CREATE INDEX idx_account_person_id ON account(person_id);

-- orchestrator module ------------------------------------------------------

CREATE TABLE auth_context (
    auth_context_id UUID PRIMARY KEY,
    account_id BIGINT NOT NULL,
    keycloak_session_id VARCHAR(255),
    keycloak_subject VARCHAR(255),
    token_handle VARCHAR(255),
    current_acr VARCHAR(50),
    current_amr JSON NOT NULL DEFAULT '[]',
    current_factor_types JSON NOT NULL DEFAULT '[]',
    auth_time TIMESTAMP NOT NULL,
    token_expires_at TIMESTAMP,
    refresh_expires_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_auth_context_account_id ON auth_context(account_id);

CREATE TABLE channel_session (
    channel_session_id UUID PRIMARY KEY,
    channel VARCHAR(20) NOT NULL,
    binding_key_ref VARCHAR(64) NOT NULL,
    account_id BIGINT,
    auth_context_id UUID,
    state VARCHAR(50) NOT NULL DEFAULT 'ANONYMOUS',
    required_acr VARCHAR(50),
    created_at TIMESTAMP NOT NULL,
    last_accessed_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_channel_session_auth_context FOREIGN KEY (auth_context_id) REFERENCES auth_context(auth_context_id)
);
CREATE INDEX idx_channel_session_binding_key_ref ON channel_session(binding_key_ref);
CREATE INDEX idx_channel_session_state ON channel_session(state);

CREATE TABLE process_session (
    process_session_id UUID PRIMARY KEY,
    channel_session_id UUID NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL,
    account_id BIGINT,
    person_id BIGINT,
    required_acr VARCHAR(50),
    starting_acr VARCHAR(50),
    achieved_acr VARCHAR(50),
    next_type VARCHAR(10),
    next_tool_id VARCHAR(50),
    next_context VARCHAR(50),
    next_step VARCHAR(50),
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_process_session_channel_session FOREIGN KEY (channel_session_id) REFERENCES channel_session(channel_session_id)
);
CREATE INDEX idx_process_session_channel_session_id ON process_session(channel_session_id);
CREATE INDEX idx_process_session_state ON process_session(state);

CREATE TABLE session_event (
    event_id UUID PRIMARY KEY,
    channel_session_id UUID,
    process_session_id UUID,
    event_type VARCHAR(100) NOT NULL,
    source VARCHAR(100) NOT NULL,
    payload_hash VARCHAR(128),
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_session_event_channel_session_id ON session_event(channel_session_id);
CREATE INDEX idx_session_event_process_session_id ON session_event(process_session_id);

CREATE TABLE tool_session (
    tool_session_id UUID PRIMARY KEY,
    process_session_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_tool_session_process_session FOREIGN KEY (process_session_id) REFERENCES process_session(process_session_id)
);
CREATE INDEX idx_tool_session_process_session_id ON tool_session(process_session_id);
