-- Baseline schema for the target model described in docs/02-domaenenmodell.md,
-- docs/03-tool-architektur.md and docs/06-ablaeufe.md. Replaces the incremental
-- V1-V16 history of the earlier Attempt-based model (see docs/11-umsetzungsplan.md).

-- ext_stammdaten module -----------------------------------------------------

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kvnr VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255),
    vorname VARCHAR(255),
    strasse VARCHAR(255),
    hausnummer VARCHAR(20),
    plz VARCHAR(10),
    ort VARCHAR(255)
);

-- id_fsc module ---------------------------------------------------------

CREATE TABLE fsc_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_fsc_code_person_id ON fsc_code(person_id);

CREATE TABLE id_fsc_tool_data (
    tool_session_id UUID PRIMARY KEY,
    kvnr VARCHAR(20),
    -- resolved by the orchestrator via ext_stammdaten and handed in, so id_fsc never
    -- depends on the ext_stammdaten module directly (docs/08-projektrahmen.md #3: leaf
    -- modules stay decoupled from each other).
    person_id BIGINT,
    name VARCHAR(255),
    vorname VARCHAR(255),
    fsc VARCHAR(50),
    created_at TIMESTAMP NOT NULL
);

-- auth_sms module ---------------------------------------------------------

-- Long-lived, confirmed SMS enrollment. Exists only after a successful TAN
-- check; no "validated" flag needed by definition (docs/06-ablaeufe.md #1).
CREATE TABLE auth_sms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(25) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped enrollment data (unconfirmed phone number + hashed TAN).
CREATE TABLE enroll_sms_tool_data (
    tool_session_id UUID PRIMARY KEY,
    phone_number VARCHAR(25),
    issued_tan_hash VARCHAR(255),
    tan_expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped auth data (resolved enrollment reference + hashed TAN).
CREATE TABLE auth_sms_use_tool_data (
    tool_session_id UUID PRIMARY KEY,
    enrollment_ref_type VARCHAR(50),
    enrollment_ref_id VARCHAR(50),
    issued_tan_hash VARCHAR(255),
    tan_expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

-- account module ---------------------------------------------------------

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    identifications JSON NOT NULL DEFAULT '[]',
    authentication_methods JSON NOT NULL DEFAULT '[]'
);
CREATE INDEX idx_account_person_id ON account(person_id);

-- orchestrator module ------------------------------------------------------

CREATE TABLE auth_context (
    auth_context_id UUID PRIMARY KEY,
    account_id BIGINT NOT NULL,
    keycloak_session_id VARCHAR(255),
    keycloak_subject VARCHAR(255),
    token_handle VARCHAR(255),
    current_acr VARCHAR(50),
    current_amr JSON NOT NULL DEFAULT '[]',
    current_factor_types JSON NOT NULL DEFAULT '[]',
    auth_time TIMESTAMP NOT NULL,
    token_expires_at TIMESTAMP,
    refresh_expires_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_auth_context_account_id ON auth_context(account_id);

CREATE TABLE channel_session (
    channel_session_id UUID PRIMARY KEY,
    channel VARCHAR(20) NOT NULL,
    binding_key_ref VARCHAR(64) NOT NULL,
    account_id BIGINT,
    auth_context_id UUID,
    state VARCHAR(50) NOT NULL DEFAULT 'ANONYMOUS',
    -- Durable lower bound of the channel; distinct from a single step-up run's targetAcr
    -- (docs/04-orchestrierung.md, "Zwei Ebenen für das geforderte Niveau").
    acr_floor VARCHAR(50),
    -- The intent this channel was entered with; resume and cancel restart the same one.
    entry_intent VARCHAR(20) NOT NULL DEFAULT 'FAST',
    created_at TIMESTAMP NOT NULL,
    last_accessed_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_channel_session_auth_context FOREIGN KEY (auth_context_id) REFERENCES auth_context(auth_context_id)
);
CREATE INDEX idx_channel_session_binding_key_ref ON channel_session(binding_key_ref);
CREATE INDEX idx_channel_session_state ON channel_session(state);

-- One run of one AuthIntent (docs/04-orchestrierung.md). `state_type`/`state` hold the
-- intent-specific JourneyState: the discriminator stays queryable, the attributes travel as
-- JSON. There is deliberately no next_* column - `next` is derived from the state.
CREATE TABLE auth_journey (
    journey_id UUID PRIMARY KEY,
    channel_session_id UUID NOT NULL,
    intent VARCHAR(20) NOT NULL,
    lifecycle VARCHAR(20) NOT NULL,
    account_id BIGINT,
    state_type VARCHAR(50) NOT NULL,
    state JSON NOT NULL,
    attempt_budget INT NOT NULL,
    -- Set on a journey started as the precondition of another one; the parent is SUSPENDED
    -- meanwhile, so at most one STARTED journey per channel remains the invariant.
    parent_journey_id UUID,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_auth_journey_channel_session FOREIGN KEY (channel_session_id) REFERENCES channel_session(channel_session_id)
);
CREATE INDEX idx_auth_journey_channel_session_id ON auth_journey(channel_session_id);
CREATE INDEX idx_auth_journey_lifecycle ON auth_journey(lifecycle);
CREATE INDEX idx_auth_journey_parent ON auth_journey(parent_journey_id);

CREATE TABLE session_event (
    event_id UUID PRIMARY KEY,
    channel_session_id UUID,
    journey_id UUID,
    event_type VARCHAR(100) NOT NULL,
    source VARCHAR(100) NOT NULL,
    payload_hash VARCHAR(128),
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_session_event_channel_session_id ON session_event(channel_session_id);
CREATE INDEX idx_session_event_journey_id ON session_event(journey_id);

-- No retry_count: the attempt budget spans the whole journey, not a single tool
-- (docs/04-orchestrierung.md, Versuchsbudget).
CREATE TABLE tool_session (
    tool_session_id UUID PRIMARY KEY,
    journey_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_tool_session_journey FOREIGN KEY (journey_id) REFERENCES auth_journey(journey_id)
);
CREATE INDEX idx_tool_session_journey_id ON tool_session(journey_id);
