-- Consolidated schema (docs/02-domaenenmodell.md, docs/07-betrieb.md). Sized for >= 10M accounts
-- and a long operating life; the rules below apply to every table and are not repeated per table.
--
-- Ownership
--   * One database schema per module, and every table lives in its owning module's schema. The
--     owner is therefore structural, not a naming convention somebody has to keep up: a table
--     cannot be created in the wrong place by accident, and "which module owns this?" is answered
--     by where it is, not by how it is spelled. Table names stay short because the schema already
--     carries the module (account.anchor, auth_sms.enrollment).
--   * Foreign keys exist only WITHIN a schema. A reference into another module is an indexed plain
--     column, cleaned up through that module's API (EnrollmentCleanup, AccountDeletionService),
--     never by a cross-schema cascade - that is the same rule as before, now visible in the DDL
--     itself rather than only in this comment.
--   * A long-lived credential table is <module>.enrollment, and that qualified name IS its
--     EnrollmentRef.type.
--   * The working data of one tool run is <module>.<tool role>_tool_session
--     (auth_qr.confirm_tool_session for confirm-qr-login). Its key IS the tool_session_id: the row
--     is the module's half of orchestrator.tool_session, not a fourth session level and not one
--     row per attempt - a run survives several failed attempts (AuthJourney.attempt_budget).
--
-- Account model
--   * account.account is identity key and optimistic-lock root only. Current state lives in rows
--     keyed by account (account.anchor, account.auth_method) and bumps its version when it
--     changes; history is append-only (account.attribute, account.identification) and never does.
--
-- Types and names
--   * Surrogate keys: BIGINT GENERATED BY DEFAULT AS IDENTITY for long-lived rows, UUID for
--     session-scoped rows. The key column is always "id"; a reference is "<table>_id".
--   * Points in time: TIMESTAMP WITH TIME ZONE. Enum values: VARCHAR(32). ACR levels: VARCHAR(16).
--     Tool ids, method names, attribute types, claim sources: VARCHAR(50). Digests: VARCHAR(64).
--   * Indexes and constraints are schema-scoped objects, so they carry no module prefix either:
--     ux_<table>_<cols> (unique), ix_<table>_<cols>. Every retention sweep has an index on its
--     cutoff column.

CREATE SCHEMA IF NOT EXISTS account;
CREATE SCHEMA IF NOT EXISTS ext_stammdaten;
CREATE SCHEMA IF NOT EXISTS orchestrator;
CREATE SCHEMA IF NOT EXISTS id_fsc;
CREATE SCHEMA IF NOT EXISTS id_eid;
CREATE SCHEMA IF NOT EXISTS auth_sms;
CREATE SCHEMA IF NOT EXISTS auth_password;
CREATE SCHEMA IF NOT EXISTS auth_email;
CREATE SCHEMA IF NOT EXISTS auth_device;
CREATE SCHEMA IF NOT EXISTS auth_qr;

-- =============================================================================================
-- ext_stammdaten: mock of the external person register
-- =============================================================================================

CREATE TABLE ext_stammdaten.person (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kvnr         VARCHAR(20)  NOT NULL,
    name         VARCHAR(255),
    vorname      VARCHAR(255),
    geburtsdatum DATE,
    strasse      VARCHAR(255),
    hausnummer   VARCHAR(20),
    plz          VARCHAR(10),
    ort          VARCHAR(255),
    CONSTRAINT ux_person_kvnr UNIQUE (kvnr)
);

-- =============================================================================================
-- account
-- =============================================================================================

CREATE TABLE account.account (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version    BIGINT NOT NULL DEFAULT 0
);

-- The one current, normalized value per (account, anchor attribute) - the only resolve-identity
-- and uniqueness authority for it. AccountProfile.personId/email/emailConfirmedAt read from here.
CREATE TABLE account.anchor (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT       NOT NULL,
    attribute_type   VARCHAR(50)  NOT NULL,
    normalized_value VARCHAR(255) NOT NULL,
    -- What was actually proven when this value was bound, capped the same way
    -- account.auth_method.enrolled_under_acr is (ADR-5) - never the level a tool merely claims.
    -- Written against AttributeType.anchorAcrFloor, which also refuses a write below it.
    established_loa  VARCHAR(16),
    established_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ux_anchor_account_type UNIQUE (account_id, attribute_type),
    CONSTRAINT ux_anchor_value UNIQUE (attribute_type, normalized_value),
    CONSTRAINT fk_anchor_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);

-- Append-only claim log: every attribute value ever asserted, with its source and level.
-- auth_method_id names the method instance whose enrollment established the claim, so revoking
-- that method can retract exactly what it asserted; NULL for claims from identification tools,
-- which produce no credential at all.
CREATE TABLE account.attribute (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT       NOT NULL,
    attribute_type   VARCHAR(50)  NOT NULL,
    attribute_value  VARCHAR(255) NOT NULL,
    normalized_value VARCHAR(255) NOT NULL,
    claim_source     VARCHAR(50)  NOT NULL,
    established_loa  VARCHAR(16),
    auth_method_id   UUID,
    established_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_attribute_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);
CREATE INDEX ix_attribute_account_id ON account.attribute (account_id);
-- Covers IdentityMatchingService's attribute-combination query entirely from the index.
CREATE INDEX ix_attribute_type_value ON account.attribute (attribute_type, normalized_value, account_id);
-- "What did this method instance ever assert?" - the retraction path's only query.
CREATE INDEX ix_attribute_auth_method_id ON account.attribute (auth_method_id);

-- A withdrawn value (ADR-12). Deliberately its own row rather than a flag on the claim: the log
-- above never mutates, so "what was asserted when" stays reconstructible, and the withdrawal
-- carries the same provenance discipline as an assertion - WHO withdrew it (trust_anchor), why
-- and when. Matching reads assertions MINUS retractions; an anchor whose value is retracted is
-- deleted outright, because account.anchor is projection, not log.
CREATE TABLE account.retraction (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT       NOT NULL,
    attribute_type   VARCHAR(50)  NOT NULL,
    normalized_value VARCHAR(255) NOT NULL,
    trust_anchor     VARCHAR(32)  NOT NULL,
    reason           VARCHAR(255),
    retracted_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_retraction_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);
-- The anti-join shape of the matching query: (type, value) first, account last.
CREATE INDEX ix_retraction_type_value ON account.retraction (attribute_type, normalized_value, account_id);

-- Append-only audit record of every identification run: which procedure, at which level, when,
-- and the proof anchors it produced (docs/06-ablaeufe.md, "dass und wie", never "was").
CREATE TABLE account.identification (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT      NOT NULL,
    method        VARCHAR(50) NOT NULL,
    achieved_loa  VARCHAR(16),
    identified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    details       JSON,
    CONSTRAINT fk_identification_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);
CREATE INDEX ix_identification_account_id ON account.identification (account_id, identified_at);

-- One registered method instance. (enrollment_type, enrollment_id) points at the credential row in
-- the owning method module; deactivated rows stay, so deletion still finds every credential.
CREATE TABLE account.auth_method (
    id                 UUID         PRIMARY KEY,
    account_id         BIGINT       NOT NULL,
    method             VARCHAR(50)  NOT NULL,
    enrollment_type    VARCHAR(50)  NOT NULL,
    enrollment_id      VARCHAR(255) NOT NULL,
    active             BOOLEAN      NOT NULL,
    enrolled_under_acr VARCHAR(16),
    label              VARCHAR(100),
    details            JSON,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    deactivated_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_auth_method_deactivation CHECK (active = (deactivated_at IS NULL)),
    CONSTRAINT fk_auth_method_account FOREIGN KEY (account_id) REFERENCES account.account (id) ON DELETE CASCADE
);
CREATE INDEX ix_auth_method_account_id ON account.auth_method (account_id, method);
-- Reverse direction: credential -> accounts (revocation sweeps, orphan checks per method module).
CREATE INDEX ix_auth_method_enrollment ON account.auth_method (enrollment_type, enrollment_id);

-- =============================================================================================
-- orchestrator (core)
-- =============================================================================================

-- Evidence proven on one channel; cleared at logout. current ACR is never stored, always derived.
CREATE TABLE orchestrator.auth_evidence (
    id           UUID   PRIMARY KEY,
    account_id   BIGINT NOT NULL,
    amr_evidence JSON   NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    version      BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX ix_auth_evidence_account_id ON orchestrator.auth_evidence (account_id);

-- APP-channel token bookkeeping.
CREATE TABLE orchestrator.auth_context (
    id                   UUID   PRIMARY KEY,
    account_id           BIGINT NOT NULL,
    auth_evidence_id     UUID,
    keycloak_session_id  VARCHAR(64),
    -- Both hold the token itself (a full JWT under the keycloak profile), not an opaque handle -
    -- hence the length. Cache only: cleared whenever the evidence changes (AuthEvidenceService),
    -- so a step-up can never keep renewing a session on pre-step-up acr/amr.
    access_token         VARCHAR(4096),
    refresh_token        VARCHAR(4096),
    auth_time            TIMESTAMP WITH TIME ZONE NOT NULL,
    access_expires_at    TIMESTAMP WITH TIME ZONE,
    refresh_expires_at   TIMESTAMP WITH TIME ZONE,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    version              BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_auth_context_auth_evidence FOREIGN KEY (auth_evidence_id) REFERENCES orchestrator.auth_evidence (id)
);
CREATE INDEX ix_auth_context_account_id ON orchestrator.auth_context (account_id);
CREATE INDEX ix_auth_context_auth_evidence_id ON orchestrator.auth_context (auth_evidence_id);

CREATE TABLE orchestrator.channel_session (
    id                    UUID        PRIMARY KEY,
    channel               VARCHAR(32) NOT NULL,
    -- APP channels anchor on the DPoP key, KEYCLOAK channels have none (docs/02-domaenenmodell.md #1).
    binding_key_ref       VARCHAR(64),
    channel_anchor        VARCHAR(64),
    kc_durable_session_id VARCHAR(64),
    account_id            BIGINT,
    auth_context_id       UUID,
    auth_evidence_id      UUID,
    state                 VARCHAR(32) NOT NULL,
    acr_floor             VARCHAR(16),
    entry_intent          VARCHAR(32) NOT NULL,
    available_tools       JSON        NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    last_accessed_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_channel_session_binding_key CHECK ((channel = 'APP') = (binding_key_ref IS NOT NULL)),
    CONSTRAINT fk_channel_session_auth_context FOREIGN KEY (auth_context_id) REFERENCES orchestrator.auth_context (id),
    CONSTRAINT fk_channel_session_auth_evidence FOREIGN KEY (auth_evidence_id) REFERENCES orchestrator.auth_evidence (id)
);
CREATE INDEX ix_channel_session_account_id ON orchestrator.channel_session (account_id);
CREATE INDEX ix_channel_session_expires_at ON orchestrator.channel_session (expires_at);
CREATE INDEX ix_channel_session_channel_expires_at ON orchestrator.channel_session (channel, expires_at);
CREATE INDEX ix_channel_session_auth_context_id ON orchestrator.channel_session (auth_context_id);
CREATE INDEX ix_channel_session_auth_evidence_id ON orchestrator.channel_session (auth_evidence_id);

-- One run of one AuthIntent. state_type keeps the JourneyState queryable; there is deliberately no
-- next_* column, next is derived from state. parent_journey_id has no FK: parent and child age out
-- independently in retention batches.
CREATE TABLE orchestrator.auth_journey (
    id                 UUID         PRIMARY KEY,
    channel_session_id UUID         NOT NULL,
    parent_journey_id  UUID,
    intent             VARCHAR(32)  NOT NULL,
    lifecycle          VARCHAR(32)  NOT NULL,
    account_id         BIGINT,
    state_type         VARCHAR(100) NOT NULL,
    state              JSON         NOT NULL,
    attempt_budget     INT          NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at        TIMESTAMP WITH TIME ZONE,
    version            BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_auth_journey_channel_session FOREIGN KEY (channel_session_id) REFERENCES orchestrator.channel_session (id)
);
CREATE INDEX ix_auth_journey_channel_session ON orchestrator.auth_journey (channel_session_id, lifecycle, created_at);
CREATE INDEX ix_auth_journey_expires_at ON orchestrator.auth_journey (expires_at);
CREATE INDEX ix_auth_journey_consumed_at ON orchestrator.auth_journey (consumed_at);

-- Lifecycle metadata only; toolId comes from the route, tool data lives in the module.
CREATE TABLE orchestrator.tool_session (
    id         UUID PRIMARY KEY,
    journey_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version    BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_tool_session_auth_journey FOREIGN KEY (journey_id) REFERENCES orchestrator.auth_journey (id)
);
CREATE INDEX ix_tool_session_journey_id ON orchestrator.tool_session (journey_id);
CREATE INDEX ix_tool_session_expires_at ON orchestrator.tool_session (expires_at);

CREATE TABLE orchestrator.device_account_link (
    binding_key_ref VARCHAR(64) PRIMARY KEY,
    account_id      BIGINT      NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_device_account_link_account_id ON orchestrator.device_account_link (account_id);

-- Minimized audit trail. Session ids are historical values, not references: it outlives them.
CREATE TABLE orchestrator.session_event (
    id                 UUID         PRIMARY KEY,
    channel_session_id UUID,
    journey_id         UUID,
    event_type         VARCHAR(100) NOT NULL,
    source             VARCHAR(100) NOT NULL,
    payload_hash       VARCHAR(128),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_session_event_created_at ON orchestrator.session_event (created_at);

-- Rich debugging trace, deliberately not minimized (unlike orchestrator.session_event); short retention.
CREATE TABLE orchestrator.journey_log (
    id                 UUID         PRIMARY KEY,
    channel_session_id UUID         NOT NULL,
    journey_id         UUID,
    parent_journey_id  UUID,
    account_id         BIGINT,
    binding_key_ref    VARCHAR(64),
    channel_type       VARCHAR(32),
    intent             VARCHAR(32),
    event_type         VARCHAR(100) NOT NULL,
    journey_state      VARCHAR(100),
    detail             JSON,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_journey_log_channel_session_id ON orchestrator.journey_log (channel_session_id, created_at);
CREATE INDEX ix_journey_log_account_id ON orchestrator.journey_log (account_id, created_at);
CREATE INDEX ix_journey_log_binding_key_ref ON orchestrator.journey_log (binding_key_ref, created_at);
CREATE INDEX ix_journey_log_created_at ON orchestrator.journey_log (created_at);

-- One counter per (scope, subject); scope is part of the key so the subject spaces never collide.
CREATE TABLE orchestrator.attempt_throttle (
    scope        VARCHAR(32)  NOT NULL,
    subject      VARCHAR(128) NOT NULL,
    failed_count INT          NOT NULL DEFAULT 0,
    locked_until TIMESTAMP WITH TIME ZONE,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_attempt_throttle PRIMARY KEY (scope, subject)
);
CREATE INDEX ix_attempt_throttle_updated_at ON orchestrator.attempt_throttle (updated_at);

-- The primary key insert IS the replay check. Keyed by SHA-256(thumbprint:jti): fixed width, and a
-- client-chosen jti can neither overflow the key nor bloat the hottest index in the system.
CREATE TABLE orchestrator.dpop_proof_replay (
    proof_hash VARCHAR(64) PRIMARY KEY,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_dpop_proof_replay_expires_at ON orchestrator.dpop_proof_replay (expires_at);

-- Runtime kill-switch per tool; no row = enabled.
CREATE TABLE orchestrator.tool_availability (
    tool_id    VARCHAR(50) PRIMARY KEY,
    enabled    BOOLEAN     NOT NULL,
    reason     VARCHAR(255),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- One row per runtime feature flag; no row = off, the documented default of that flag. flag_key
-- is a FeatureFlags constant (e.g. 'register-enroll-first'), never free-form: a strategy reads the
-- name from that object, so a typo here simply leaves the flag off rather than inventing one.
CREATE TABLE orchestrator.feature_flag (
    flag_key   VARCHAR(100) PRIMARY KEY,
    enabled    BOOLEAN      NOT NULL,
    reason     VARCHAR(255),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- keycloak profile: per-account keypair for the account-token grant. Demo-only: private key in
-- plaintext. Removed by KeycloakAccountSyncListener once the account deletion has committed.
CREATE TABLE orchestrator.keycloak_keypair (
    account_id      BIGINT        PRIMARY KEY,
    public_key_jwk  VARCHAR(2000) NOT NULL,
    private_key_jwk VARCHAR(2000) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- =============================================================================================
-- id_fsc
-- =============================================================================================

-- A Freischaltcode stays reusable until it expires; guessing is bounded by the PERSON throttle.
CREATE TABLE id_fsc.code (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id  BIGINT      NOT NULL,
    code_hash  VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_code_person_id ON id_fsc.code (person_id, code_hash);

CREATE TABLE id_fsc.ident_tool_session (
    tool_session_id UUID PRIMARY KEY,
    kvnr            VARCHAR(20),
    person_id       BIGINT,
    name            VARCHAR(255),
    vorname         VARCHAR(255),
    fsc_hash        VARCHAR(64),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_ident_tool_session_created_at ON id_fsc.ident_tool_session (created_at);

-- =============================================================================================
-- id_eid
-- =============================================================================================

CREATE TABLE id_eid.ident_tool_session (
    tool_session_id UUID PRIMARY KEY,
    kvnr            VARCHAR(20),
    person_id       BIGINT,
    name            VARCHAR(255),
    vorname         VARCHAR(255),
    geburtsdatum    DATE,
    strasse         VARCHAR(255),
    hausnummer      VARCHAR(20),
    plz             VARCHAR(10),
    ort             VARCHAR(255),
    pin_hash        VARCHAR(64),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_ident_tool_session_created_at ON id_eid.ident_tool_session (created_at);

-- =============================================================================================
-- auth_sms
-- =============================================================================================

-- Exists only after a successful TAN check, so it is confirmed by definition.
CREATE TABLE auth_sms.enrollment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(32) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE auth_sms.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    phone_number    VARCHAR(32),
    issued_tan_hash VARCHAR(64),
    tan_expires_at  TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_sms.enroll_tool_session (created_at);

CREATE TABLE auth_sms.auth_tool_session (
    tool_session_id     UUID PRIMARY KEY,
    enrollment_ref_type VARCHAR(50),
    enrollment_ref_id   VARCHAR(255),
    issued_tan_hash     VARCHAR(64),
    tan_expires_at      TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_sms.auth_tool_session (created_at);

-- account_id is only known after the first PATCH resolved it.
CREATE TABLE auth_sms.lookup_tool_session (
    tool_session_id UUID PRIMARY KEY,
    account_id      BIGINT,
    issued_tan_hash VARCHAR(64),
    tan_expires_at  TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lookup_tool_session_created_at ON auth_sms.lookup_tool_session (created_at);

-- =============================================================================================
-- auth_password
-- =============================================================================================

-- No identifier of its own: the account's EMAIL anchor identifies it.
CREATE TABLE auth_password.enrollment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE auth_password.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_password.enroll_tool_session (created_at);

CREATE TABLE auth_password.auth_tool_session (
    tool_session_id     UUID PRIMARY KEY,
    enrollment_ref_type VARCHAR(50),
    enrollment_ref_id   VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_password.auth_tool_session (created_at);

CREATE TABLE auth_password.lookup_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lookup_tool_session_created_at ON auth_password.lookup_tool_session (created_at);

-- =============================================================================================
-- auth_email (no enrollment table: the credential is the account's EMAIL anchor)
-- =============================================================================================

CREATE TABLE auth_email.confirm_tool_session (
    tool_session_id  UUID PRIMARY KEY,
    email            VARCHAR(255),
    issued_code_hash VARCHAR(64),
    code_expires_at  TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_confirm_tool_session_created_at ON auth_email.confirm_tool_session (created_at);

-- One row per enroll-email run. No columns of its own: activating the method proves nothing, the
-- address was already established by confirm-email.
CREATE TABLE auth_email.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_email.enroll_tool_session (created_at);

CREATE TABLE auth_email.auth_tool_session (
    tool_session_id  UUID PRIMARY KEY,
    issued_code_hash VARCHAR(64),
    code_expires_at  TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_email.auth_tool_session (created_at);

CREATE TABLE auth_email.lookup_tool_session (
    tool_session_id  UUID PRIMARY KEY,
    account_id       BIGINT,
    issued_code_hash VARCHAR(64),
    code_expires_at  TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lookup_tool_session_created_at ON auth_email.lookup_tool_session (created_at);

-- =============================================================================================
-- auth_device
-- =============================================================================================

-- The credential is the public half of a non-extractable device key pair.
CREATE TABLE auth_device.enrollment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kty        VARCHAR(10)  NOT NULL,
    crv        VARCHAR(10)  NOT NULL,
    x          VARCHAR(255) NOT NULL,
    y          VARCHAR(255) NOT NULL,
    thumbprint VARCHAR(64)  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ux_enrollment_thumbprint UNIQUE (thumbprint)
);

CREATE TABLE auth_device.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_device.enroll_tool_session (created_at);

CREATE TABLE auth_device.auth_tool_session (
    tool_session_id     UUID PRIMARY KEY,
    enrollment_ref_type VARCHAR(50),
    enrollment_ref_id   VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_device.auth_tool_session (created_at);

-- =============================================================================================
-- auth_qr
-- =============================================================================================

-- Pure opt-in marker ("this account allows QR login"), no secret.
CREATE TABLE auth_qr.enrollment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Connects a WEB auth-qr activation to an APP confirm-qr-login decision. pairing_code IS the
-- lookup capability; verification_code is only compared by eye.
CREATE TABLE auth_qr.login_request (
    pairing_code         VARCHAR(16) PRIMARY KEY,
    verification_code    VARCHAR(8)  NOT NULL,
    expected_account_id  BIGINT,
    status               VARCHAR(32) NOT NULL,
    resolving_account_id BIGINT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_login_request_expires_at ON auth_qr.login_request (expires_at);

CREATE TABLE auth_qr.enroll_tool_session (
    tool_session_id UUID PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_enroll_tool_session_created_at ON auth_qr.enroll_tool_session (created_at);

CREATE TABLE auth_qr.auth_tool_session (
    tool_session_id UUID PRIMARY KEY,
    pairing_code    VARCHAR(16) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_tool_session_created_at ON auth_qr.auth_tool_session (created_at);

CREATE TABLE auth_qr.lookup_tool_session (
    tool_session_id UUID PRIMARY KEY,
    pairing_code    VARCHAR(16) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_lookup_tool_session_created_at ON auth_qr.lookup_tool_session (created_at);

CREATE TABLE auth_qr.confirm_tool_session (
    tool_session_id UUID PRIMARY KEY,
    pairing_code    VARCHAR(16),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_confirm_tool_session_created_at ON auth_qr.confirm_tool_session (created_at);
