-- account module -----------------------------------------------------------
-- Log of every identity attribute ever claimed for an account, each with its own trust anchor
-- and the LOA it was established at (docs/ideen/claims-modell-und-vertrauensanker.md, Phase 1:
-- log only, nothing reads it back yet). account's own columns (person_id, email, ...) remain
-- the actively consolidated projection, written straight through by the existing paths.
-- Consolidation precedence once something reads this back: anchor class first, recency only
-- as tiebreaker (ADR-11, docs/12-entscheidungen.md). Retractions will be a separate table
-- when they arrive (ADR-12). UNIQUE(person_id) is deliberately NOT here - issue iuq covers it.
-- ON DELETE CASCADE: the log is the account's own provenance record - it has no meaning without
-- its account, so deleting the account deletes its log with it; deleteAccount's "row only, callers
-- clean up their own modules' tables" contract with FOREIGN modules stays unchanged.

CREATE TABLE account_attribute (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    attribute_type VARCHAR(50) NOT NULL,
    attribute_value VARCHAR(255) NOT NULL,
    trust_anchor VARCHAR(50) NOT NULL,
    established_loa VARCHAR(10),
    established_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_account_attribute_account_id ON account_attribute(account_id);
