-- auth_password module ---------------------------------------------------

-- Long-lived, confirmed username/password credential. Created directly on
-- enrollment - a chosen password is self-verifying, no "unconfirmed" state.
CREATE TABLE auth_password (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped enrollment data (invariant marker: start() ran before patch()).
CREATE TABLE enroll_password_tool_data (
    tool_session_id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL
);

-- Attempt-scoped auth data (resolved enrollment reference).
CREATE TABLE auth_password_use_tool_data (
    tool_session_id UUID PRIMARY KEY,
    enrollment_ref_type VARCHAR(50),
    enrollment_ref_id VARCHAR(50),
    created_at TIMESTAMP NOT NULL
);
